### ISSUE TITLE
How to send only 1 gem in trade offer ?

### ISSUE THREAD

**Issue by SENPAY98K** [Koncealed/node-steam-trade-farms#26]
I would like to know how to add only 1 gem in the trade offer  ?

Also it would be very easy to boost trades by sending 1 gem to some alt account ( with auto accept donation)
and keep it going.. hope you can help make this possible :)

**Comment by Rulzius** [comment]
> I would like to know how to add only 1 gem in the trade offer ?
> 
> Also it would be very easy to boost trades by sending 1 gem to some alt account ( with auto accept donation) and keep it going.. hope you can help make this possible :)

Hi did you find anything helpful about that idea?

**Comment by SENPAY98K** [comment]
> > I would like to know how to add only 1 gem in the trade offer ?
> > Also it would be very easy to boost trades by sending 1 gem to some alt account ( with auto accept donation) and keep it going.. hope you can help make this possible :)
> 
> Hi did you find anything helpful about that idea?

https://discord.gg/NNF3uF5fwM
