### ISSUE TITLE
Can't get shared secret (I have SDA)

### ISSUE THREAD

**Issue by teasimon** [Koncealed/node-steam-trade-farms#28]
can't find it in MaFiles

**Comment by Koncealed** [comment]
You cannot encrypt the files.

**Comment by teasimon** [comment]
then how am i supposed to get shared secret and the other thing

**Comment by Koncealed** [comment]
When its unencrypted.

**Comment by teasimon** [comment]
is it ever gonna turn unencrypted?

**Comment by Koncealed** [comment]
You have to set the option in SDA.

**Comment by teasimon** [comment]
do you know what causes this?
![image](https://user-images.githubusercontent.com/68283261/126141433-14c476b6-f0dc-4b37-816c-db4d18140657.png)

**Comment by Koncealed** [comment]
sadly no. You might want to make an issue with SDA.

**Comment by teasimon** [comment]
anyways thanks for your help :)
